# Generated by Django 4.0 on 2022-02-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oyun_ad_soyad', models.CharField(max_length=25)),
                ('meslek', models.CharField(max_length=25)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
