# Generated by Django 4.0 on 2022-02-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hablerler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basik', models.CharField(max_length=30)),
                ('aciklama', models.TextField(blank=True, max_length=250, null=True)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='haberler')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
