# Generated by Django 4.0 on 2022-02-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_hablerler_haberler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haberler',
            old_name='basik',
            new_name='baslik',
        ),
    ]
