# Generated by Django 4.0 on 2022-02-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='baslik',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
