# Generated by Django 4.0 on 2022-02-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_form_soru10_cevap_alter_form_soru1_cevap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='soru1',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='soru3_cevap',
            field=models.CharField(blank=True, choices=[('1', 'Kesinlikle Katılmıyorum'), ('2', 'Katılmıyorum'), ('3', 'Kararsızım'), ('4', 'Katılıyorum'), ('5', 'Kesinlikle Katılıyorum')], max_length=64, null=True),
        ),
    ]
