# Generated by Django 4.0 on 2022-02-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_form_soru1_alter_form_soru3_cevap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='soru1',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
