# Generated by Django 4.0 on 2022-02-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_form_soru1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='soru1',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
