# Generated by Django 4.0 on 2022-02-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_form_kayitli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=30)),
                ('soru1', models.TextField(blank=True, max_length=50, null=True)),
                ('soru2', models.TextField(blank=True, max_length=50, null=True)),
                ('soru3', models.TextField(blank=True, max_length=50, null=True)),
                ('soru4', models.TextField(blank=True, max_length=50, null=True)),
                ('soru5', models.TextField(blank=True, max_length=50, null=True)),
                ('soru6', models.TextField(blank=True, max_length=50, null=True)),
                ('soru7', models.TextField(blank=True, max_length=50, null=True)),
                ('soru8', models.TextField(blank=True, max_length=50, null=True)),
                ('soru9', models.TextField(blank=True, max_length=50, null=True)),
                ('soru10', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='baslik',
        ),
        migrations.RemoveField(
            model_name='form',
            name='soru1',
        ),
        migrations.RemoveField(
            model_name='form',
            name='soru10',
        ),
        migrations.RemoveField(
            model_name='form',
            name='soru2',
        ),
        migrations.RemoveField(
            model_name='form',
            name='soru3',
        ),
        migrations.RemoveField(
            model_name='form',
            name='soru4',
        ),
        migrations.RemoveField(
            model_name='form',
            name='soru5',
        ),
        migrations.RemoveField(
            model_name='form',
            name='soru6',
        ),
        migrations.RemoveField(
            model_name='form',
            name='soru7',
        ),
        migrations.RemoveField(
            model_name='form',
            name='soru8',
        ),
        migrations.RemoveField(
            model_name='form',
            name='soru9',
        ),
    ]
