# Generated by Django 4.0 on 2022-02-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_sorular_remove_form_baslik_remove_form_soru1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorular',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sorular',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
