# Generated by Django 4.0 on 2022-02-16 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_sorular_guncellenme_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorular',
            name='cevaplar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.form'),
        ),
    ]
