# Generated by Django 4.0 on 2022-02-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_sorular_cevaplar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorular',
            name='cevaplar',
        ),
    ]
