# Generated by Django 4.0 on 2022-02-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_form_soru10_cevap_alter_form_soru1_cevap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorular',
            name='baslik',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
