# Generated by Django 4.0 on 2022-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_form_sorular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='sorular',
        ),
        migrations.AddField(
            model_name='form',
            name='sorular',
            field=models.ManyToManyField(blank=True, null=True, to='base.Sorular'),
        ),
    ]
