# Generated by Django 4.0 on 2022-02-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_form_baslik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='sorular',
        ),
    ]
