# Generated by Django 4.0 on 2022-02-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0025_form_sorular'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Cevaplar',
        ),
    ]
