# Generated by Django 4.0 on 2022-02-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_cevaplar_soru11_cevap_cevaplar_soru12_cevap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cevaplar',
            name='onay1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='onay2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='onay3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='onay4',
            field=models.BooleanField(default=True),
        ),
    ]
