# Generated by Django 4.0 on 2022-02-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_cevaplar_onay1_cevaplar_onay2_cevaplar_onay3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cevaplar',
            old_name='onay1',
            new_name='onay1_cevap',
        ),
        migrations.RenameField(
            model_name='cevaplar',
            old_name='onay2',
            new_name='onay2_cevap',
        ),
        migrations.RenameField(
            model_name='cevaplar',
            old_name='onay3',
            new_name='onay3_cevap',
        ),
        migrations.RenameField(
            model_name='cevaplar',
            old_name='onay4',
            new_name='onay4_cevap',
        ),
        migrations.AddField(
            model_name='sorular',
            name='onay1',
            field=models.CharField(default=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sorular',
            name='onay2',
            field=models.CharField(default=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sorular',
            name='onay3',
            field=models.CharField(default=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sorular',
            name='onay4',
            field=models.CharField(default=True, max_length=60),
        ),
    ]
