# Generated by Django 4.0 on 2022-02-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rename_onay1_cevaplar_onay1_cevap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorular',
            name='onay1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sorular',
            name='onay2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sorular',
            name='onay3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sorular',
            name='onay4',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
