# Generated by Django 4.0 on 2022-02-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_cevaplar_baslik_alter_sorular_baslik'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnayDurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onaydurum', models.CharField(blank=True, choices=[('Bekle', 'Bekle'), ('Kabul Et', 'Kabul Et'), ('Reddet', 'Reddet')], max_length=8, null=True)),
            ],
        ),
    ]
