# Generated by Django 4.0 on 2022-03-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_onaydurum_onaydurum'),
    ]

    operations = [
        migrations.AddField(
            model_name='haberler',
            name='baslik_slug',
            field=models.SlugField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
