# Generated by Django 4.0 on 2022-03-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_cevaplar_baslik_slug_sorular_baslik_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='oyun_ad_soyad_slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
