# Generated by Django 4.0 on 2022-03-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0047_kisi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kisi',
            new_name='OnayUser',
        ),
    ]
