# Generated by Django 4.0 on 2022-03-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_rename_kisi_onayuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onaydurum',
            name='kisi',
        ),
    ]
