# Generated by Django 4.0 on 2022-03-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_iletisim_guncellenme_tarihi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iletisim',
            name='user',
        ),
    ]
