# Generated by Django 4.0 on 2022-03-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_iletisim_user_iletisim_cevap_guncellenme_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iletisim_cevap',
            name='iletisim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.iletisim'),
        ),
    ]
