# Generated by Django 4.0 on 2022-03-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_profilfoto_biyografi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilfoto',
            name='arka_plan',
            field=models.ImageField(blank=True, null=True, upload_to='arka_plan'),
        ),
    ]
