# Generated by Django 4.0 on 2022-03-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_forumsoru_baslik_forumsoru_guncellenme_tarihi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumsorucevap',
            name='user',
        ),
        migrations.AddField(
            model_name='forumsorucevap',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profilfoto'),
        ),
    ]
