# Generated by Django 4.0 on 2022-03-24 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_profilfoto_username_profilfoto_username_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumsoru',
            name='user',
        ),
        migrations.AddField(
            model_name='forumsoru',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profilfoto'),
        ),
    ]
