# Generated by Django 4.0 on 2022-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_formcevabacevap'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsorucevap',
            name='cevaba_cevap',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='FormCevabaCevap',
        ),
    ]
