# Generated by Django 4.0 on 2022-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_alter_forumsorucevap_cevaba_cevap'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsoru',
            name='baslik_slug',
            field=models.SlugField(default=3, unique=True),
            preserve_default=False,
        ),
    ]
