# Generated by Django 4.0 on 2022-03-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_forumsoru_baslik_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsorucevap',
            name='cevaba_cevap',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
