# Generated by Django 4.0 on 2022-03-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_forumsorucevap_begenme_forumsorucevap_begenmeme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumsorucevap',
            name='begenmeme',
        ),
    ]
