# Generated by Django 4.0 on 2022-03-31 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0083_remove_forumsorucevap_begenmeme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumsorucevap',
            name='begenme',
        ),
        migrations.AddField(
            model_name='forumsorucevap',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumsorucevap',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
