# Generated by Django 4.0 on 2022-04-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsoru',
            name='yanit_sayi',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
