# Generated by Django 4.0 on 2022-04-17 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsoru',
            name='dislikes',
            field=models.ManyToManyField(blank=True, default=None, related_name='dislikes1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumsoru',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumsoru',
            name='onay_durum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.onaydurum'),
        ),
        migrations.AddField(
            model_name='forumsoru',
            name='yanit_sayi',
            field=models.CharField(blank=True, default='0', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='forumsorucevap',
            name='onay_durum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.onaydurum'),
        ),
    ]
