# Generated by Django 4.0 on 2022-02-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_hablerler'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hablerler',
            new_name='Haberler',
        ),
    ]
