# Generated by Django 4.0 on 2022-04-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_forumsoru_yanit_sayi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsoru',
            name='yanit_sayi',
            field=models.CharField(blank=True, default='0', max_length=12, null=True),
        ),
    ]
