# Generated by Django 4.0 on 2022-04-26 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_forumsorucevap_cevap'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsoru',
            name='goruldu',
            field=models.ManyToManyField(blank=True, default=None, related_name='goruldu', to=settings.AUTH_USER_MODEL),
        ),
    ]
