# Generated by Django 4.0 on 2022-04-10 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_forumsoru_yanit_sayi'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsoru',
            name='dislikes',
            field=models.ManyToManyField(blank=True, default=None, related_name='dislikes1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumsoru',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes1', to=settings.AUTH_USER_MODEL),
        ),
    ]
