# Generated by Django 4.0 on 2022-04-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_forumsoru_dislikes_forumsoru_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumsoru',
            name='dislikes',
        ),
    ]
