# Generated by Django 4.0 on 2022-04-26 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_forumsoru_goruldu'),
    ]

    operations = [
        migrations.AddField(
            model_name='haberler',
            name='goruldu',
            field=models.ManyToManyField(blank=True, default=None, related_name='goruldu_haber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iletisim',
            name='goruldu',
            field=models.ManyToManyField(blank=True, default=None, related_name='goruldu_iletisim', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iletisim_cevap',
            name='goruldu',
            field=models.ManyToManyField(blank=True, default=None, related_name='goruldu_iletisim_cevap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='goruldu',
            field=models.ManyToManyField(blank=True, default=None, related_name='goruldu_oyuncu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sorular',
            name='goruldu',
            field=models.ManyToManyField(blank=True, default=None, related_name='goruldu_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumsoru',
            name='goruldu',
            field=models.ManyToManyField(blank=True, default=None, related_name='goruldu_soru', to=settings.AUTH_USER_MODEL),
        ),
    ]
