# Generated by Django 4.0 on 2022-04-12 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_forumsoru_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilfoto',
            name='onay_durum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.onaydurum'),
        ),
    ]
