# Generated by Django 4.0 on 2022-02-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_form_baslik_form_guncellenme_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='soru10_cevap',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='soru1_cevap',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='soru2_cevap',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='soru3_cevap',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='soru4_cevap',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='soru5_cevap',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='soru6_cevap',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='soru7_cevap',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='soru8_cevap',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='soru9_cevap',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=64, null=True),
        ),
    ]
