# Generated by Django 4.0 on 2022-04-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profilfoto_onay_durum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilfoto',
            name='onay_durum',
        ),
    ]
