# Generated by Django 4.0 on 2022-04-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_profilfoto_onay_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsorucevap',
            name='onay_durum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.onaydurum'),
        ),
    ]
