# Generated by Django 4.0 on 2022-04-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_forumsoru_soru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsoru',
            name='soru',
            field=models.TextField(max_length=500),
        ),
    ]
