# Generated by Django 4.0 on 2022-04-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_forumsoru_onay_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsoru',
            name='likes_ids',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
