# Generated by Django 4.0 on 2022-04-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_kullanici_hikayesi_alter_kullanici_meslek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iletisim',
            name='dosya',
        ),
    ]
