# Generated by Django 4.0 on 2022-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_forumsoru_likes_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsoru',
            name='dislikes_ids',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
