# Generated by Django 4.0 on 2022-04-14 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_forumsoru_dislikes_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumsoru',
            name='dislikes_ids',
        ),
        migrations.RemoveField(
            model_name='forumsoru',
            name='likes_ids',
        ),
        migrations.AddField(
            model_name='forumsoru',
            name='dislikes',
            field=models.ManyToManyField(blank=True, default=None, related_name='dislikes1', to=settings.AUTH_USER_MODEL),
        ),
    ]
