# Generated by Django 4.0 on 2022-05-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_forumsoru_onay_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='oyun_ad_soyad',
            field=models.CharField(max_length=40),
        ),
    ]
