# Generated by Django 4.0 on 2022-05-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_kullanici_oyun_ad_soyad'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='hikaye',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
