# Generated by Django 4.0 on 2022-05-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_profilfoto_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='hikaye',
            field=models.TextField(max_length=800),
        ),
    ]
