# Generated by Django 4.0 on 2022-05-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_kullanici_hikaye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumsoru',
            name='yanit_sayi',
        ),
        migrations.AlterField(
            model_name='haberler',
            name='aciklama',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='haberler',
            name='baslik',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='hikaye',
            field=models.TextField(max_length=5200),
        ),
    ]
