# Generated by Django 4.0 on 2022-06-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_forumsoru_baslik_alter_forumsoru_soru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumsoru',
            name='baslik_slug',
        ),
    ]
