# Generated by Django 4.0 on 2022-06-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_sorular_baslik_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='hikaye',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='sorular',
            name='soru12',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
