# Generated by Django 4.0 on 2022-02-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_form_sorular_form_sorular'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='baslik',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
