# Generated by Django 4.0 on 2022-07-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_kullanici_hikaye_alter_sorular_soru12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevaplar',
            name='soru12_cevap',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='sorular',
            name='soru12',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
