# Generated by Django 4.0 on 2022-07-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_cevaplar_soru12_cevap_alter_sorular_soru12'),
    ]

    operations = [
        migrations.AddField(
            model_name='cevaplar',
            name='soru19_cevap',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sorular',
            name='soru19',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
