# Generated by Django 4.0 on 2022-02-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_form_cevaplar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cevaplar',
            name='soru11_cevap',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='soru12_cevap',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='soru13_cevap',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='soru14_cevap',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='soru15_cevap',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='soru16_cevap',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='soru17_cevap',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='soru18_cevap',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sorular',
            name='soru11',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sorular',
            name='soru12',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sorular',
            name='soru13',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sorular',
            name='soru14',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sorular',
            name='soru15',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sorular',
            name='soru16',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sorular',
            name='soru17',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sorular',
            name='soru18',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
