# Generated by Django 4.0 on 2022-07-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_profilfoto_takip_edilenler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilfoto',
            name='takip_edilenler',
        ),
        migrations.RemoveField(
            model_name='profilfoto',
            name='takipciler',
        ),
    ]
