# Generated by Django 4.0 on 2022-07-05 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0028_remove_profilfoto_takip_edilenler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilfoto',
            name='takip_edilenler',
            field=models.ManyToManyField(blank=True, default=None, related_name='takip_edilenler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilfoto',
            name='takipciler',
            field=models.ManyToManyField(blank=True, default=None, related_name='takipciler', to=settings.AUTH_USER_MODEL),
        ),
    ]
