# Generated by Django 4.0 on 2022-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_profilfoto_takip_edilenler_profilfoto_takipciler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hareketler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
