# Generated by Django 4.0 on 2022-07-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_hareketler_admin_mi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hareketler',
            new_name='Hareket',
        ),
    ]
