# Generated by Django 4.0 on 2022-08-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_hareket_guncellenme_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onaydurum',
            name='onaydurum',
            field=models.CharField(blank=True, choices=[('Kabul Et', 'Kabul Et'), ('Bekle', 'Bekle'), ('Reddet', 'Reddet'), ('Kalıcı Olarak Reddet', 'Kalıcı Olarak Reddet'), ('Yasakla', 'Yasakla'), ('Cevapsız', 'Cevapsız')], max_length=40, null=True),
        ),
    ]
