# Generated by Django 4.0 on 2022-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_onaydurum_onaydurum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevaplar',
            name='soru12_cevap',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='hikaye',
            field=models.TextField(max_length=20000),
        ),
    ]
