# Generated by Django 4.0 on 2022-09-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_cevaplar_soru12_cevap_alter_kullanici_hikaye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='oyun_ad_soyad',
            field=models.CharField(max_length=40, verbose_name='Adı Soyadı'),
        ),
    ]
