# Generated by Django 4.0 on 2022-09-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_kullanici_oyun_ad_soyad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='oyun_ad_soyad_slug',
            field=models.SlugField(),
        ),
    ]
