# Generated by Django 4.0 on 2022-03-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_onaydurum_guncellenme_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onaydurum',
            name='onaydurum',
            field=models.CharField(blank=True, choices=[('Kabul Et', 'Kabul Et'), ('Bekle', 'Bekle'), ('Reddet', 'Reddet'), ('Yasakla', 'Yasakla')], max_length=8, null=True),
        ),
    ]
