# Generated by Django 4.0 on 2022-03-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_cevaplar_onay1_cevap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevaplar',
            name='soru12_cevap',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cevaplar',
            name='soru17_cevap',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
