# Generated by Django 4.0 on 2022-03-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_iletisim_cevap_iletisim'),
    ]

    operations = [
        migrations.AddField(
            model_name='iletisim',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='iletisim',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='iletisim',
            name='dosya',
            field=models.ImageField(blank=True, null=True, upload_to='iletisim'),
        ),
    ]
