# Generated by Django 4.0 on 2022-03-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_forumsorucevap_guncellenme_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilfoto',
            name='biyografi',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
