# Generated by Django 4.0 on 2022-03-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_profilfoto_arka_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilfoto',
            name='biyografi',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
