# Generated by Django 4.0 on 2022-03-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_remove_forumsorucevap_user_forumsorucevap_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilfoto',
            name='username',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='profilfoto',
            name='username_slug',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
