# Generated by Django 4.0 on 2022-03-25 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_remove_forumsoru_user_forumsoru_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCevabaCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevap', models.CharField(max_length=1000)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, null=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, null=True)),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profilfoto')),
                ('soru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.forumsorucevap')),
            ],
        ),
    ]
