# Generated by Django 4.0 on 2022-03-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_alter_forumsorucevap_cevaba_cevap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsorucevap',
            name='cevaba_cevap',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
