# Generated by Django 4.0 on 2022-03-31 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0081_alter_forumsorucevap_cevaba_cevap'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsorucevap',
            name='begenme',
            field=models.ManyToManyField(related_name='begenme', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumsorucevap',
            name='begenmeme',
            field=models.ManyToManyField(related_name='begenmeme', to=settings.AUTH_USER_MODEL),
        ),
    ]
